//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApps.aciafServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="aciafServiceReference.IACIAF")]
    public interface IACIAF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACIAF/GetData", ReplyAction="http://tempuri.org/IACIAF/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACIAF/GetData", ReplyAction="http://tempuri.org/IACIAF/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACIAF/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IACIAF/GetDataUsingDataContractResponse")]
        serviceACIAF.CompositeType GetDataUsingDataContract(serviceACIAF.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACIAF/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IACIAF/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<serviceACIAF.CompositeType> GetDataUsingDataContractAsync(serviceACIAF.CompositeType composite);
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadArchivedAgentRequest) of message DownloadArchivedAgentRequest does not match the default value (SendAgentInstanceArchiveToRemoteACIAFServer)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACIAF/SendAgentInstanceArchiveToRemoteACIAFServer", ReplyAction="http://tempuri.org/IACIAF/SendAgentInstanceArchiveToRemoteACIAFServerResponse")]
        testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo SendAgentInstanceArchiveToRemoteACIAFServer(testApps.aciafServiceReference.DownloadArchivedAgentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACIAF/SendAgentInstanceArchiveToRemoteACIAFServer", ReplyAction="http://tempuri.org/IACIAF/SendAgentInstanceArchiveToRemoteACIAFServerResponse")]
        System.Threading.Tasks.Task<testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo> SendAgentInstanceArchiveToRemoteACIAFServerAsync(testApps.aciafServiceReference.DownloadArchivedAgentRequest request);
        
        // CODEGEN: Generating message contract since the operation ReceiveAgentInstanceArchiveFROMRemoteACIAFServer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACIAF/ReceiveAgentInstanceArchiveFROMRemoteACIAFServer", ReplyAction="http://tempuri.org/IACIAF/ReceiveAgentInstanceArchiveFROMRemoteACIAFServerRespons" +
            "e")]
        testApps.aciafServiceReference.ReceiveAgentInstanceArchiveFROMRemoteACIAFServerResponse ReceiveAgentInstanceArchiveFROMRemoteACIAFServer(testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACIAF/ReceiveAgentInstanceArchiveFROMRemoteACIAFServer", ReplyAction="http://tempuri.org/IACIAF/ReceiveAgentInstanceArchiveFROMRemoteACIAFServerRespons" +
            "e")]
        System.Threading.Tasks.Task<testApps.aciafServiceReference.ReceiveAgentInstanceArchiveFROMRemoteACIAFServerResponse> ReceiveAgentInstanceArchiveFROMRemoteACIAFServerAsync(testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadArchivedAgentRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadArchivedAgentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FileName;
        
        public DownloadArchivedAgentRequest() {
        }
        
        public DownloadArchivedAgentRequest(string FileName) {
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteACIAFAgentInstanceArchiveFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteACIAFAgentInstanceArchiveFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteACIAFAgentInstanceArchiveFileInfo() {
        }
        
        public RemoteACIAFAgentInstanceArchiveFileInfo(string FileName, long Length, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveAgentInstanceArchiveFROMRemoteACIAFServerResponse {
        
        public ReceiveAgentInstanceArchiveFROMRemoteACIAFServerResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IACIAFChannel : testApps.aciafServiceReference.IACIAF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ACIAFClient : System.ServiceModel.ClientBase<testApps.aciafServiceReference.IACIAF>, testApps.aciafServiceReference.IACIAF {
        
        public ACIAFClient() {
        }
        
        public ACIAFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ACIAFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACIAFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACIAFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public serviceACIAF.CompositeType GetDataUsingDataContract(serviceACIAF.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<serviceACIAF.CompositeType> GetDataUsingDataContractAsync(serviceACIAF.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo testApps.aciafServiceReference.IACIAF.SendAgentInstanceArchiveToRemoteACIAFServer(testApps.aciafServiceReference.DownloadArchivedAgentRequest request) {
            return base.Channel.SendAgentInstanceArchiveToRemoteACIAFServer(request);
        }
        
        public long SendAgentInstanceArchiveToRemoteACIAFServer(ref string FileName, out System.IO.Stream FileByteStream) {
            testApps.aciafServiceReference.DownloadArchivedAgentRequest inValue = new testApps.aciafServiceReference.DownloadArchivedAgentRequest();
            inValue.FileName = FileName;
            testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo retVal = ((testApps.aciafServiceReference.IACIAF)(this)).SendAgentInstanceArchiveToRemoteACIAFServer(inValue);
            FileName = retVal.FileName;
            FileByteStream = retVal.FileByteStream;
            return retVal.Length;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo> testApps.aciafServiceReference.IACIAF.SendAgentInstanceArchiveToRemoteACIAFServerAsync(testApps.aciafServiceReference.DownloadArchivedAgentRequest request) {
            return base.Channel.SendAgentInstanceArchiveToRemoteACIAFServerAsync(request);
        }
        
        public System.Threading.Tasks.Task<testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo> SendAgentInstanceArchiveToRemoteACIAFServerAsync(string FileName) {
            testApps.aciafServiceReference.DownloadArchivedAgentRequest inValue = new testApps.aciafServiceReference.DownloadArchivedAgentRequest();
            inValue.FileName = FileName;
            return ((testApps.aciafServiceReference.IACIAF)(this)).SendAgentInstanceArchiveToRemoteACIAFServerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testApps.aciafServiceReference.ReceiveAgentInstanceArchiveFROMRemoteACIAFServerResponse testApps.aciafServiceReference.IACIAF.ReceiveAgentInstanceArchiveFROMRemoteACIAFServer(testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo request) {
            return base.Channel.ReceiveAgentInstanceArchiveFROMRemoteACIAFServer(request);
        }
        
        public void ReceiveAgentInstanceArchiveFROMRemoteACIAFServer(string FileName, long Length, System.IO.Stream FileByteStream) {
            testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo inValue = new testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            testApps.aciafServiceReference.ReceiveAgentInstanceArchiveFROMRemoteACIAFServerResponse retVal = ((testApps.aciafServiceReference.IACIAF)(this)).ReceiveAgentInstanceArchiveFROMRemoteACIAFServer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testApps.aciafServiceReference.ReceiveAgentInstanceArchiveFROMRemoteACIAFServerResponse> testApps.aciafServiceReference.IACIAF.ReceiveAgentInstanceArchiveFROMRemoteACIAFServerAsync(testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo request) {
            return base.Channel.ReceiveAgentInstanceArchiveFROMRemoteACIAFServerAsync(request);
        }
        
        public System.Threading.Tasks.Task<testApps.aciafServiceReference.ReceiveAgentInstanceArchiveFROMRemoteACIAFServerResponse> ReceiveAgentInstanceArchiveFROMRemoteACIAFServerAsync(string FileName, long Length, System.IO.Stream FileByteStream) {
            testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo inValue = new testApps.aciafServiceReference.RemoteACIAFAgentInstanceArchiveFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((testApps.aciafServiceReference.IACIAF)(this)).ReceiveAgentInstanceArchiveFROMRemoteACIAFServerAsync(inValue);
        }
    }
}
